/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Wed Dec 15 15:47:50 2021 */

/* parameterized module instance */
PLL_block __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
